### ISSUE TITLE
Installation on VueJS without NPM

### ISSUE THREAD

**Issue by panagath** [alexsabdev/vue-drift#14]
Hi. I'm not using NPM to install my VueJS. I do it directly in my html file. 

I import vuejs as:

    <script  src="https://unpkg.com/vue@latest/dist/vue.js"></script>

and tried to import the vue-drift.min.js

with the following:

      Vue.use(VueDrift, {
        appId: 'My-app-id',
      })
      Vue.component('vue-drift', VueDrift);

But it does not work. Always get the error: VueDrift is not defined.
Do you have any guide on how to install directly without npm?

**Comment by alexsabdev** [comment]
@panagath thanks for reaching out. It must be because of a lack of browser env support. I just pushed an update. Please follow this instruction and let me konw if it works for you: https://github.com/alexsabdev/vue-drift#browser-environment. Please make sure you are using a version 2.1.0 as UNPKG may take some time to invalidate its cache.
